#!/usr/bin/env sh

if [[ `whoami` != 'laralgeria' ]]; then
    echo 'This script must be run as the "laralgeria" user. Rerunning...'
    sudo -E -u laralgeria letsencrypt_renew $@
    exit 1
fi

certbot renew --webroot -w /var/www/letsencrypt $*