version: '2.2'

services:
  web:
    container_name: laralgeria_web_v1
    build:
      context: ./docker-containers/laralgeria-web
      args:
        TIMEZONE: "${TIMEZONE:-Africa/Algiers}"
    ports:
      - "${LARALGERIA_HTTP_PORT:-80}:80"
      - "${LARALGERIA_HTTPS_PORT:-443}:443"
    depends_on:
      - db
    env_file: laralgeria.env
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./${APP_FOLDER_NAME:-main-domain}:/var/laralgeria/www
    restart: always
    logging: &default-logging
      options:
        max-size: "1m"
        max-file: "5"

  db:
    container_name: laralgeria_db_v1
    build:
      context: ./docker-containers/laralgeria-db
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file: laralgeria.env
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    logging: *default-logging

volumes:
  letsencrypt: {}
  db_data: {}
  www_data: {}
